version: "3"
services:
  mail:
    image: bytemark/smtp
    container_name: emailserver 
    restart: always
  backend:
    build: ./emailBackend
    container_name: backendportfolio 
    ports:
      - 8005:8005
    volumes:
      - ./emailBackend:/code
  web:
    build: ./web
    container_name: webportfolio 
    ports:
      - 3000:3000
    volumes:
      - ./web:/code
